homeassistant:
  # Omitted values in this section will be auto detected using freegeoip.io

  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 322
  # Name of the location where Home Assistant is running
  name: Home
  # C for Celcius, F for Fahrenheit
  temperature_unit: F
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  unit_system: imperial
  customize: !include customize.yaml
  packages: !include_dir_named packages
python_script:
zone:
  name: Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  radius: 200
  icon: mdi:home

zone 2:
  name: Buckhead
  latitude: !secret latitude_buckhead
  longitude: !secret longitude_buckhead
  radius: 200
  icon: mdi:school

zone 3:
  name: Downtown
  latitude: !secret latitude_downtown
  longitude: !secret longitude_downtown
  radius: 200
  icon: mdi:school
zwave:
  usb_path: /dev/ttyACM0
  # new_entity_ids: true
  network_key: !secret zwave_network_key
light:
  - platform: lifx
  # z-wave dimmer switch (http://amzn.to/2j1UEli)
  - platform: mqtt
    name: "Kitchen Lights"
    state_topic: "smartthings/Kitchen/switch"
    command_topic: "smartthings/Kitchen/switch"
    payload_on: "on"
    payload_off: "off"
    brightness_state_topic: "smartthings/Kitchen/level"
    brightness_command_topic: "smartthings/Kitchen/level"
    brightness_scale: 99
    brightness_value_template: '{{ value }}'
    retain: true
    optimistic: false
    qos: 0

#Adds Alexa and Google Home support
emulated_hue:
  host_ip: !secret hass_ip
  expose_by_default: false
  listen_port: 80
# Enables the frontend
frontend:
  themes:
    minimal:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    stormy_hues:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    vintage:
      dark-primary-color: "#373f27"
      primary-color: "#636b46"
      light-primary-color: "#e9e7da"
      paper-toggle-button-checked-ink-color: "#cda34f"
      paper-toggle-button-checked-button-color: "#cda34f"
      paper-toggle-button-checked-bar-color: "#cda34f"
      paper-slider-knob-color: "#cda34f"
      paper-slider-knob-start-color: "#cda34f"
      paper-slider-pin-color: "#cda34f"
      paper-slider-active-color: "#cda34f"
    done1:
      dark-primary-color: "#565656"
      primary-color: "#C09F80"
      light-primary-color: "#D7CEC7"
      paper-toggle-button-checked-ink-color: "#76323F"
      paper-toggle-button-checked-button-color: "#76323F"
      paper-toggle-button-checked-bar-color: "#76323F"
      paper-slider-knob-color: "#76323F"
      paper-slider-knob-start-color: "#76323F"
      paper-slider-pin-color: "#76323F"
      paper-slider-active-color: "#76323F"
      paper-slider-secondary-color: "#FFE0B2"
media_extractor:
# Enables configuration UI
config:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 3
  trusted_networks:
    - 192.168.2.0/24

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv
wemo:
updater:
  include_used_components: true

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

camera:
  - platform: bloomsky
    # Generate your link - https://www.wunderground.com/weather-radar/united-states/
  - platform: generic
    still_image_url: 'https://icons.wxug.com/data/weather-maps/radar/united-states/columbus-georgia-region-current-radar-animation.gif'
    name: WundergroundRadar
  - platform: synology
    url: http://192.168.2.113:5000/
    username: !secret synology_username
    password: !secret synology_password
  # - platform: opencv
  #   camera: camera.motoe
  #   processor: image_processing.opencv_motoe
  #   name: OpenCV MotoE
  # - platform: opencv
  #   camera: camera.porch
  #   processor: image_processing.opencv_porch
  #   name: OpenCV Porch
  # - platform: opencv
  #   camera: camera.patio
  #   processor: image_processing.opencv_patio
  #   name: OpenCV Patio
  # - platform: opencv
  #   camera: camera.backyard
  #   processor: image_processing.opencv_backyard
  #   name: OpenCV Backyard
  # - platform: opencv
  #   camera: camera.driveway
  #   processor: image_processing.opencv_driveway
  #   name: OpenCV Driveway
  # - platform: generic
  #   still_image_url: 'https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=FFC&brand=wui&num=1&delay=100&type=NTP&frame=0&scale=1&noclutter=0&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=24427697&lat=0&lon=0&label=you'
  #   name: RadarGA
    # Generate link - http://www.intellicast.com/National/Radar/Current.aspx
  # - platform: generic
  #   still_image_url: 'http://images.intellicast.com/WxImages/RadarLoop/prc_None_anim.gif'
  #   name: IntellicastRadar
  # - platform: generic
  #   still_image_url: !secret porch_camera_image_url
  #   name: porch2

ring:
  username: !secret ring_username
  password: !secret ring_password
bloomsky:
  api_key: !secret bloomsky_key

ifttt:
  key: !secret ifttt_key

# android_ip_webcam:
#   - host: 192.168.2.176
#     name: motoe
#     scan_interval: 1
image_processing:
  - platform: dlib_face_detect
    keep_faces: True
    keep_no_faces: False
    source:
      - entity_id: camera.porch
        name: "Face Detected porch"
      - entity_id: camera.backyard
        name: "Face Detected backyard"
      - entity_id: camera.driveway
        name: "Face Detected driveway"
      - entity_id: camera.patio
        name: "Face Detected patio"
#   - platform: opencv
#     name: OpenCV
#     source:
#       - entity_id: camera.porch
#       - entity_id: camera.motoe
#     classifier:
#       body: /home/homeassistant/.homeassistant/classifier/haarcascade_frontalface_default.xml
#       neighbors: 5

sun:
media_player:
  - platform: sonos
    hosts: 192.168.2.150
  - platform: kodi
    host: http://192.168.2.28
    port: 8080
    name: Kodi NSTV
    username: !secret kodi_username
    password: !secret kodi_password
  - platform: panasonic_viera
    host: 192.168.2.128
    port: 55000
    name: Panasonic Viera TV
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  # - platform: plex
  #   host: 192.168.2.212
  # - platform: apple_tv
  #   host: 192.168.2.90
  #   login_id: !secret apple_hsgid

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: unifi
    host: 192.168.2.163
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: False
  # - platform: asuswrt
  #   host: 192.168.2.1
  #   protocol: telnet
  #   username: !secret asus_username
  #   password: !secret asus_password

telegram_bot:
  platform: polling
  api_key: !secret telegram_key
  allowed_chat_ids:
    - !secret telegram_chatID_Alok

notify:
  - platform: ios
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - name: telegram
    platform: telegram
    api_key: !secret telegram_key
    chat_id: !secret telegram_chatID_Alok
  - platform: ecobee
    name: ecobee
  - name: iOS
    platform: group
    services:
      - service: ios_alokiosiphone
      - service: ios_rashmiappiphone

ecobee:
  api_key: !secret ecobee_key
  hold_temp: True

# Log Severities: notset, debug, info, warn, warning, error, fatal, critical
logger:
  default: error
  logs:
    homeassistant.components.image_processing: error
    homeassistant.components.python_script: warning
# Text to speech
tts:
  - platform: google
    cache: true
    cache_dir: /home/homeassistant/.homeassistant/tts
    time_memory: 300
  - platform: voicerss
    api_key: !secret voicerss_key
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    text_type: ssml
    cache: True    
remote:
  - platform: harmony
    name: livingroom
    host: 192.168.2.152
ios:
scene:
  platform: lifx_cloud
  token: !secret lifx_key
mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant-1
  username: !secret mqtt_username
  password: !secret mqtt_password
# View all events in a logbook
logbook:
  exclude:
    domains:
      - sun
    entities:
      - sensor.pws_weather
      - sensor.pws_temp_f
      - sensor.pws_relative_humidity
      - binary_sensor.ars_bloom_rain
      - binary_sensor.ars_bloom_night
      - binary_sensor.garage_door_tilt_sensor_sensor
      - binary_sensor.upstairs_occupancy
      - binary_sensor.downstairs_occupancy
      - binary_sensor.porch_field_detection
      - binary_sensor.patio_field_detection
      - binary_sensor.driveway_field_detection
      - binary_sensor.backyard_field_detection
      - binary_sensor.backyard_line_crossing
      - binary_sensor.driveway_line_crossing
      - binary_sensor.patio_line_crossing
      - binary_sensor.porch_line_crossing
      - sensor.ars_bloom_uvindex
      - sensor.pws_wind_dir
      - sensor.pws_wind_string
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_daily_summary
      - sensor.time__date
      - sensor.bloomlastupdate
      - sensor.garage_door_tilt_sensor_alarm_level
      - sensor.garage_door_tilt_sensor_alarm_type
      - sensor.garage_door_tilt_sensor_burglar
      - sensor.garage_door_tilt_sensor_sourcenodeid
      - sensor.garagedoorbattery
      - sensor.phonebatteryalok
      - sensor.phonebatteryrashmi
      - sensor.usd_inr
      - sensor.usd_eur
      - sensor.sonos_volume
      - sensor.downstairsthermoper
      - sensor.upstairsthermostatoperation
      - group.abode_status
      - group.device_location
      - group.information
      - group.thermostats
      - group.media_player
      - group.weather
      - group.devices
      - group.all_lights
      - group.household
      - group.entertainment
      - group.switches
      - group.camera_switches
      - device_tracker.unificloudkey
      - media_player.unnamed_device
      - media_player.livingroomsonos
      - media_player.plex_web_chrome_2
      - media_player.plex_web_chrome
      - automation.update_volume_slider
      - automation.heal_zwave_network
      - automation.set_volume
      - automation.turn_tv_onoff
      - automation.start_harmony_activity_from_input_select
      - automation.update_ha_if_harmony_activity_changes
      - automation.update_tv_status_in_ha
      - automation.plex_spy_notification
      - automation.reset_garage_relay
      - automation.open_garage_door_when_someone_home
      - automation.rashmi_home
      - automation.alok_home
      - automation.notify_camera_pictures
      - zwave.garage_relay
      - zwave.aeotec_zw090_zstick_gen5
      - zwave.garage_door_tilt_sensor
      - input_slider.harmonyvolume
      - input_boolean.leeoalarm
      - input_boolean.thermo_away_main
      - input_boolean.thermo_away_upstairs
      - binary_sensor.ring_front_door_ding
      - binary_sensor.ring_front_door_motion
      - sensor.ring_front_door_last_activity
      - sensor.ring_front_door_last_ding
      - sensor.ring_front_door_last_motion
      - sensor.transmission_down_speed
      - sensor.transmission_status
      - sensor.transmission_up_speed
# Enables support for tracking state changes over time.
history:
  include:
    entities:
      - binary_sensor.garagedoor
      - device_tracker.alokiosiphone
      - device_tracker.myiphone
      - device_tracker.pi_alokphone
      - device_tracker.alok_alok
      - device_tracker.pi_rashmiphone
      - device_tracker.rashmiappiphone
      - device_tracker.rashmisiphone
      - device_tracker.sonu_sonu
      - device_tracker.meta_rashmi
      - device_tracker.meta_alok
      - input_select.abodestatus
      - media_player.panasonic_viera_tv
      - sensor.plexspy
recorder:
  purge_days: 3
  db_url: !secret recorder_db_url
  exclude:
    domains:
      - sun
    entities:
      - binary_sensor.backyard_motion
      - binary_sensor.driveway_motion
      - binary_sensor.patio_motion
      - binary_sensor.porch_motion
      - group.camera_sensors
      - input_slider.leeotemperature
      - input_slider.leeohumidity
      - input_slider.leeoupstairstemp
      - input_slider.leeoupstairshumidity
      - input_select.livingroomharmony
      - sensor.living_room
      - zwave.garage_door_tilt_sensor
      - automation.change_leeo_color
      - automation.change_leeo_upstairs_color
      - automation.parse_life360_data
      - group.ring_doorbell
      - sensor.pollen
      - sensor.pollen_level
      - sensor.hass_uptime
      - sensor.time__date
      - switch.pihole
      - sensor.dns_queries_today
      - sensor.domains_being_blocked
      - sensor.ads_blocked_today
      - sensor.ads_percentage_today
      - automation.populate_owntracks_data_from_life360
      - automation.update_device_meta_tracker
      - image_processing.opencv_backyard
      - image_processing.opencv_patio
      - image_processing.opencv_driveway
      - image_processing.opencv_porch
automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switches.yaml
binary_sensor: !include binary_sensor.yaml
alexa: !include alexa.yaml
apiai: !include apiai.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_slider: !include input_slider.yaml
