###############################################################################
# PACKAGE:      LIFE360 SENSOR
# Description:  The Life360 sensor requires username, password and mqtt topic.
#               Whatever the topic you specify, the data will be dumped there.
#               Use the exact topic name in the Parse Life360 Data automation.
###############################################################################

homeassistant:
  customize:
    sensor.life360_sensor:
      friendly_name: Life 360
      hidden: true

sensor:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    mqtt_topic: "/life360/data"
    scan_interval: 60

automation:

###############################################################################
# Alert me When the sensor fails
###############################################################################
  - id: life360_sensor_error
    alias: Alert Life360 Sensor Error
    initial_state: true
    hide_entity: true
    condition:
      - condition: template
        value_template: >
          {%- if states.automation.parse_life360_data.attributes.last_triggered -%}
            {{ (as_timestamp(now()) - as_timestamp(states.automation.parse_life360_data.attributes.last_triggered)) > 500 }}
          {%- else -%}
            true
          {%- endif -%}
    trigger:
      platform: state
      entity_id: sensor.life360_sensor
      from: 'running'
      to: 'error'
    action:
      - service: notify.pushbullet
        data:
          message: "Life360 Sensor"
          title: "There seem to be a problem with Life360 Sensor!"
