sensor:
  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    monitored_conditions:
      - summary
      - precip_probability
      - wind_speed
      - cloud_cover
      - icon
      - temperature_min
      - temperature_max
      - daily_summary
      - hourly_summary

  - platform: season
  - platform: template
    sensors:
      weekday:
        friendly_name: 'Weekday'
        value_template: '{{ now().strftime("%A") }}'
      forecast_today:
        friendly_name: "Today's Forecast"
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon.state ~ '.png'}}

      forecast_first:
        friendly_name: 'Tomorrow' #{{ (as_timestamp(now()) + (86400)) | timestamp_custom("%A", True) }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_1.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_1.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_1.state ~ '.png'}}

      forecast_second:
        friendly_name: 'Second' #{{ (as_timestamp(now()) + (86400) *2) | timestamp_custom("%A", True) }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_2.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_2.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_2.state ~ '.png'}}

      forecast_third:
        friendly_name: 'Third' #{{ (as_timestamp(now()) + (86400) *3) | timestamp_custom("%A", True) }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_3.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_3.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_3.state ~ '.png'}}

      forecast_fourth:
        friendly_name: 'Fourth' #{{ (as_timestamp(now()) + (86400) *4) | timestamp_custom("%A", True) }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_4.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_4.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_4.state ~ '.png'}}

      forecast_fifth:
        friendly_name: 'Fifth' #{{ (as_timestamp(now()) + (86400) *5) | timestamp_custom("%A", True) }}
        value_template: >
          {{states.sensor.dark_sky_daily_high_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_5.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_5.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_5.state ~ '.png'}}

      forecast_sixth:
        friendly_name: 'Sixth' #{{ (as_timestamp(now()) + (86400) *6) | timestamp_custom("%A", True) }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_6.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_6.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_6.state ~ '.png'}}

      forecast_seventh:
        friendly_name: 'Seventh' #{{ (as_timestamp(now()) + (86400) *7) | timestamp_custom("%A", True) }}
        value_template: >
            {{states.sensor.dark_sky_daily_high_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_daily_low_temperature_7.state|round(0)}}°/{{states.sensor.dark_sky_precip_probability_7.state|round(0)}}%
        entity_picture_template: >-
          {{ '/local/dark_sky/' ~ states.sensor.dark_sky_icon_7.state ~ '.png'}}

group:
  weather_card_forecast:
    name: Forecast
    view: no
    icon: mdi:sun
    entities:
      - sensor.forecast_first
      - sensor.forecast_second
      - sensor.forecast_third
      - sensor.forecast_fourth
      - sensor.forecast_fifth
      - sensor.forecast_sixth
      - sensor.forecast_seventh
